/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.thilenius.flame.service.thrift.genfiles;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class Spark implements org.apache.thrift.TBase<Spark, Spark._Fields>, java.io.Serializable, Cloneable, Comparable<Spark> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("Spark");

  private static final org.apache.thrift.protocol.TField SPARK_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("sparkID", org.apache.thrift.protocol.TType.I32, (short)1);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new SparkStandardSchemeFactory());
    schemes.put(TupleScheme.class, new SparkTupleSchemeFactory());
  }

  public int sparkID; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    SPARK_ID((short)1, "sparkID");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // SPARK_ID
          return SPARK_ID;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __SPARKID_ISSET_ID = 0;
  private byte __isset_bitfield = 0;
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.SPARK_ID, new org.apache.thrift.meta_data.FieldMetaData("sparkID", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(Spark.class, metaDataMap);
  }

  public Spark() {
  }

  public Spark(
    int sparkID)
  {
    this();
    this.sparkID = sparkID;
    setSparkIDIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public Spark(Spark other) {
    __isset_bitfield = other.__isset_bitfield;
    this.sparkID = other.sparkID;
  }

  public Spark deepCopy() {
    return new Spark(this);
  }

  @Override
  public void clear() {
    setSparkIDIsSet(false);
    this.sparkID = 0;
  }

  public int getSparkID() {
    return this.sparkID;
  }

  public Spark setSparkID(int sparkID) {
    this.sparkID = sparkID;
    setSparkIDIsSet(true);
    return this;
  }

  public void unsetSparkID() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __SPARKID_ISSET_ID);
  }

  /** Returns true if field sparkID is set (has been assigned a value) and false otherwise */
  public boolean isSetSparkID() {
    return EncodingUtils.testBit(__isset_bitfield, __SPARKID_ISSET_ID);
  }

  public void setSparkIDIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __SPARKID_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case SPARK_ID:
      if (value == null) {
        unsetSparkID();
      } else {
        setSparkID((Integer)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case SPARK_ID:
      return Integer.valueOf(getSparkID());

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case SPARK_ID:
      return isSetSparkID();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof Spark)
      return this.equals((Spark)that);
    return false;
  }

  public boolean equals(Spark that) {
    if (that == null)
      return false;

    boolean this_present_sparkID = true;
    boolean that_present_sparkID = true;
    if (this_present_sparkID || that_present_sparkID) {
      if (!(this_present_sparkID && that_present_sparkID))
        return false;
      if (this.sparkID != that.sparkID)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  @Override
  public int compareTo(Spark other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetSparkID()).compareTo(other.isSetSparkID());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetSparkID()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.sparkID, other.sparkID);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("Spark(");
    boolean first = true;

    sb.append("sparkID:");
    sb.append(this.sparkID);
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class SparkStandardSchemeFactory implements SchemeFactory {
    public SparkStandardScheme getScheme() {
      return new SparkStandardScheme();
    }
  }

  private static class SparkStandardScheme extends StandardScheme<Spark> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, Spark struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // SPARK_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.sparkID = iprot.readI32();
              struct.setSparkIDIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, Spark struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(SPARK_ID_FIELD_DESC);
      oprot.writeI32(struct.sparkID);
      oprot.writeFieldEnd();
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class SparkTupleSchemeFactory implements SchemeFactory {
    public SparkTupleScheme getScheme() {
      return new SparkTupleScheme();
    }
  }

  private static class SparkTupleScheme extends TupleScheme<Spark> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, Spark struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetSparkID()) {
        optionals.set(0);
      }
      oprot.writeBitSet(optionals, 1);
      if (struct.isSetSparkID()) {
        oprot.writeI32(struct.sparkID);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, Spark struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(1);
      if (incoming.get(0)) {
        struct.sparkID = iprot.readI32();
        struct.setSparkIDIsSet(true);
      }
    }
  }

}

