/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace Flame
{
  public enum MovementTypes
  {
    Forward = 1,
    Backward = 2,
    TurnLeft = 3,
    TurnRight = 4,
    Up = 5,
    Down = 6,
  }
}
