// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BFEProtos.proto

package com.thilenius.blaze.frontend.protos;

public final class BFEProtos {
  private BFEProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
    registry.add(com.thilenius.blaze.frontend.protos.BFEProtos.BFELoadLevelRequest.bFELoadLevelRequestExt);
    registry.add(com.thilenius.blaze.frontend.protos.BFEProtos.BFELoadLevelResponse.bFELoadLevelResponseExt);
    registry.add(com.thilenius.blaze.frontend.protos.BFEProtos.BFESparkCommand.bFESparkCommandExt);
    registry.add(com.thilenius.blaze.frontend.protos.BFEProtos.BFESparkResponse.bFESparkResponseExt);
  }
  public interface BFEMessageOrBuilder extends 
       com.google.protobuf.GeneratedMessageLite.
            ExtendableMessageOrBuilder<BFEMessage> {
  }
  public static final class BFEMessage extends
      com.google.protobuf.GeneratedMessageLite.ExtendableMessage<
        BFEMessage> implements BFEMessageOrBuilder {
    // Use BFEMessage.newBuilder() to construct.
    private BFEMessage(Builder builder) {
      super(builder);
    }
    private BFEMessage(boolean noInit) {}
    
    private static final BFEMessage defaultInstance;
    public static BFEMessage getDefaultInstance() {
      return defaultInstance;
    }
    
    public BFEMessage getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    private void initFields() {
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!extensionsAreInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      com.google.protobuf.GeneratedMessageLite
        .ExtendableMessage<com.thilenius.blaze.frontend.protos.BFEProtos.BFEMessage>.ExtensionWriter extensionWriter =
          newExtensionWriter();
      extensionWriter.writeUntil(536870912, output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      size += extensionsSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.thilenius.blaze.frontend.protos.BFEProtos.BFEMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.thilenius.blaze.frontend.protos.BFEProtos.BFEMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.thilenius.blaze.frontend.protos.BFEProtos.BFEMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.thilenius.blaze.frontend.protos.BFEProtos.BFEMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.thilenius.blaze.frontend.protos.BFEProtos.BFEMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.thilenius.blaze.frontend.protos.BFEProtos.BFEMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.thilenius.blaze.frontend.protos.BFEProtos.BFEMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.thilenius.blaze.frontend.protos.BFEProtos.BFEMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.thilenius.blaze.frontend.protos.BFEProtos.BFEMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.thilenius.blaze.frontend.protos.BFEProtos.BFEMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.thilenius.blaze.frontend.protos.BFEProtos.BFEMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.ExtendableBuilder<
          com.thilenius.blaze.frontend.protos.BFEProtos.BFEMessage, Builder> implements com.thilenius.blaze.frontend.protos.BFEProtos.BFEMessageOrBuilder {
      // Construct using com.thilenius.blaze.frontend.protos.BFEProtos.BFEMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.thilenius.blaze.frontend.protos.BFEProtos.BFEMessage getDefaultInstanceForType() {
        return com.thilenius.blaze.frontend.protos.BFEProtos.BFEMessage.getDefaultInstance();
      }
      
      public com.thilenius.blaze.frontend.protos.BFEProtos.BFEMessage build() {
        com.thilenius.blaze.frontend.protos.BFEProtos.BFEMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.thilenius.blaze.frontend.protos.BFEProtos.BFEMessage buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.thilenius.blaze.frontend.protos.BFEProtos.BFEMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.thilenius.blaze.frontend.protos.BFEProtos.BFEMessage buildPartial() {
        com.thilenius.blaze.frontend.protos.BFEProtos.BFEMessage result = new com.thilenius.blaze.frontend.protos.BFEProtos.BFEMessage(this);
        return result;
      }
      
      public Builder mergeFrom(com.thilenius.blaze.frontend.protos.BFEProtos.BFEMessage other) {
        if (other == com.thilenius.blaze.frontend.protos.BFEProtos.BFEMessage.getDefaultInstance()) return this;
        this.mergeExtensionFields(other);
        return this;
      }
      
      public final boolean isInitialized() {
        if (!extensionsAreInitialized()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              
              return this;
            default: {
              if (!parseUnknownField(input, extensionRegistry, tag)) {
                
                return this;
              }
              break;
            }
          }
        }
      }
      
      
      // @@protoc_insertion_point(builder_scope:Thilenius.BFEProtos.BFEMessage)
    }
    
    static {
      defaultInstance = new BFEMessage(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:Thilenius.BFEProtos.BFEMessage)
  }
  
  public interface BFELoadLevelRequestOrBuilder
      extends com.google.protobuf.MessageLiteOrBuilder {
    
    // required string auth_token = 1;
    boolean hasAuthToken();
    String getAuthToken();
    
    // required int32 levelNumber = 2;
    boolean hasLevelNumber();
    int getLevelNumber();
    
    // optional int32 seed = 3;
    boolean hasSeed();
    int getSeed();
  }
  public static final class BFELoadLevelRequest extends
      com.google.protobuf.GeneratedMessageLite
      implements BFELoadLevelRequestOrBuilder {
    // Use BFELoadLevelRequest.newBuilder() to construct.
    private BFELoadLevelRequest(Builder builder) {
      super(builder);
    }
    private BFELoadLevelRequest(boolean noInit) {}
    
    private static final BFELoadLevelRequest defaultInstance;
    public static BFELoadLevelRequest getDefaultInstance() {
      return defaultInstance;
    }
    
    public BFELoadLevelRequest getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    private int bitField0_;
    // required string auth_token = 1;
    public static final int AUTH_TOKEN_FIELD_NUMBER = 1;
    private java.lang.Object authToken_;
    public boolean hasAuthToken() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getAuthToken() {
      java.lang.Object ref = authToken_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          authToken_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getAuthTokenBytes() {
      java.lang.Object ref = authToken_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        authToken_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required int32 levelNumber = 2;
    public static final int LEVELNUMBER_FIELD_NUMBER = 2;
    private int levelNumber_;
    public boolean hasLevelNumber() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public int getLevelNumber() {
      return levelNumber_;
    }
    
    // optional int32 seed = 3;
    public static final int SEED_FIELD_NUMBER = 3;
    private int seed_;
    public boolean hasSeed() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public int getSeed() {
      return seed_;
    }
    
    private void initFields() {
      authToken_ = "";
      levelNumber_ = 0;
      seed_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasAuthToken()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLevelNumber()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getAuthTokenBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, levelNumber_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, seed_);
      }
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getAuthTokenBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, levelNumber_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, seed_);
      }
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.thilenius.blaze.frontend.protos.BFEProtos.BFELoadLevelRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.thilenius.blaze.frontend.protos.BFEProtos.BFELoadLevelRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.thilenius.blaze.frontend.protos.BFEProtos.BFELoadLevelRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.thilenius.blaze.frontend.protos.BFEProtos.BFELoadLevelRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.thilenius.blaze.frontend.protos.BFEProtos.BFELoadLevelRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.thilenius.blaze.frontend.protos.BFEProtos.BFELoadLevelRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.thilenius.blaze.frontend.protos.BFEProtos.BFELoadLevelRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.thilenius.blaze.frontend.protos.BFEProtos.BFELoadLevelRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.thilenius.blaze.frontend.protos.BFEProtos.BFELoadLevelRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.thilenius.blaze.frontend.protos.BFEProtos.BFELoadLevelRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.thilenius.blaze.frontend.protos.BFEProtos.BFELoadLevelRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.thilenius.blaze.frontend.protos.BFEProtos.BFELoadLevelRequest, Builder>
        implements com.thilenius.blaze.frontend.protos.BFEProtos.BFELoadLevelRequestOrBuilder {
      // Construct using com.thilenius.blaze.frontend.protos.BFEProtos.BFELoadLevelRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        authToken_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        levelNumber_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        seed_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.thilenius.blaze.frontend.protos.BFEProtos.BFELoadLevelRequest getDefaultInstanceForType() {
        return com.thilenius.blaze.frontend.protos.BFEProtos.BFELoadLevelRequest.getDefaultInstance();
      }
      
      public com.thilenius.blaze.frontend.protos.BFEProtos.BFELoadLevelRequest build() {
        com.thilenius.blaze.frontend.protos.BFEProtos.BFELoadLevelRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.thilenius.blaze.frontend.protos.BFEProtos.BFELoadLevelRequest buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.thilenius.blaze.frontend.protos.BFEProtos.BFELoadLevelRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.thilenius.blaze.frontend.protos.BFEProtos.BFELoadLevelRequest buildPartial() {
        com.thilenius.blaze.frontend.protos.BFEProtos.BFELoadLevelRequest result = new com.thilenius.blaze.frontend.protos.BFEProtos.BFELoadLevelRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.authToken_ = authToken_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.levelNumber_ = levelNumber_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.seed_ = seed_;
        result.bitField0_ = to_bitField0_;
        return result;
      }
      
      public Builder mergeFrom(com.thilenius.blaze.frontend.protos.BFEProtos.BFELoadLevelRequest other) {
        if (other == com.thilenius.blaze.frontend.protos.BFEProtos.BFELoadLevelRequest.getDefaultInstance()) return this;
        if (other.hasAuthToken()) {
          setAuthToken(other.getAuthToken());
        }
        if (other.hasLevelNumber()) {
          setLevelNumber(other.getLevelNumber());
        }
        if (other.hasSeed()) {
          setSeed(other.getSeed());
        }
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasAuthToken()) {
          
          return false;
        }
        if (!hasLevelNumber()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              
              return this;
            default: {
              if (!parseUnknownField(input, extensionRegistry, tag)) {
                
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              authToken_ = input.readBytes();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              levelNumber_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              seed_ = input.readInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string auth_token = 1;
      private java.lang.Object authToken_ = "";
      public boolean hasAuthToken() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getAuthToken() {
        java.lang.Object ref = authToken_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          authToken_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setAuthToken(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        authToken_ = value;
        
        return this;
      }
      public Builder clearAuthToken() {
        bitField0_ = (bitField0_ & ~0x00000001);
        authToken_ = getDefaultInstance().getAuthToken();
        
        return this;
      }
      void setAuthToken(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        authToken_ = value;
        
      }
      
      // required int32 levelNumber = 2;
      private int levelNumber_ ;
      public boolean hasLevelNumber() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public int getLevelNumber() {
        return levelNumber_;
      }
      public Builder setLevelNumber(int value) {
        bitField0_ |= 0x00000002;
        levelNumber_ = value;
        
        return this;
      }
      public Builder clearLevelNumber() {
        bitField0_ = (bitField0_ & ~0x00000002);
        levelNumber_ = 0;
        
        return this;
      }
      
      // optional int32 seed = 3;
      private int seed_ ;
      public boolean hasSeed() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public int getSeed() {
        return seed_;
      }
      public Builder setSeed(int value) {
        bitField0_ |= 0x00000004;
        seed_ = value;
        
        return this;
      }
      public Builder clearSeed() {
        bitField0_ = (bitField0_ & ~0x00000004);
        seed_ = 0;
        
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:Thilenius.BFEProtos.BFELoadLevelRequest)
    }
    
    static {
      defaultInstance = new BFELoadLevelRequest(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:Thilenius.BFEProtos.BFELoadLevelRequest)
    public static final int BFELOADLEVELREQUEST_EXT_FIELD_NUMBER = 100;
    public static final
      com.google.protobuf.GeneratedMessageLite.GeneratedExtension<
        com.thilenius.blaze.frontend.protos.BFEProtos.BFEMessage,
        com.thilenius.blaze.frontend.protos.BFEProtos.BFELoadLevelRequest> bFELoadLevelRequestExt = com.google.protobuf.GeneratedMessageLite
            .newSingularGeneratedExtension(
          com.thilenius.blaze.frontend.protos.BFEProtos.BFEMessage.getDefaultInstance(),
          com.thilenius.blaze.frontend.protos.BFEProtos.BFELoadLevelRequest.getDefaultInstance(),
          com.thilenius.blaze.frontend.protos.BFEProtos.BFELoadLevelRequest.getDefaultInstance(),
          null,
          100,
          com.google.protobuf.WireFormat.FieldType.MESSAGE);
  }
  
  public interface BFELoadLevelResponseOrBuilder
      extends com.google.protobuf.MessageLiteOrBuilder {
    
    // optional string failure_reason = 1;
    boolean hasFailureReason();
    String getFailureReason();
    
    // optional int32 spark_count = 2;
    boolean hasSparkCount();
    int getSparkCount();
  }
  public static final class BFELoadLevelResponse extends
      com.google.protobuf.GeneratedMessageLite
      implements BFELoadLevelResponseOrBuilder {
    // Use BFELoadLevelResponse.newBuilder() to construct.
    private BFELoadLevelResponse(Builder builder) {
      super(builder);
    }
    private BFELoadLevelResponse(boolean noInit) {}
    
    private static final BFELoadLevelResponse defaultInstance;
    public static BFELoadLevelResponse getDefaultInstance() {
      return defaultInstance;
    }
    
    public BFELoadLevelResponse getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    private int bitField0_;
    // optional string failure_reason = 1;
    public static final int FAILURE_REASON_FIELD_NUMBER = 1;
    private java.lang.Object failureReason_;
    public boolean hasFailureReason() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getFailureReason() {
      java.lang.Object ref = failureReason_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          failureReason_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getFailureReasonBytes() {
      java.lang.Object ref = failureReason_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        failureReason_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional int32 spark_count = 2;
    public static final int SPARK_COUNT_FIELD_NUMBER = 2;
    private int sparkCount_;
    public boolean hasSparkCount() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public int getSparkCount() {
      return sparkCount_;
    }
    
    private void initFields() {
      failureReason_ = "";
      sparkCount_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getFailureReasonBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, sparkCount_);
      }
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getFailureReasonBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, sparkCount_);
      }
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.thilenius.blaze.frontend.protos.BFEProtos.BFELoadLevelResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.thilenius.blaze.frontend.protos.BFEProtos.BFELoadLevelResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.thilenius.blaze.frontend.protos.BFEProtos.BFELoadLevelResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.thilenius.blaze.frontend.protos.BFEProtos.BFELoadLevelResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.thilenius.blaze.frontend.protos.BFEProtos.BFELoadLevelResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.thilenius.blaze.frontend.protos.BFEProtos.BFELoadLevelResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.thilenius.blaze.frontend.protos.BFEProtos.BFELoadLevelResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.thilenius.blaze.frontend.protos.BFEProtos.BFELoadLevelResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.thilenius.blaze.frontend.protos.BFEProtos.BFELoadLevelResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.thilenius.blaze.frontend.protos.BFEProtos.BFELoadLevelResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.thilenius.blaze.frontend.protos.BFEProtos.BFELoadLevelResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.thilenius.blaze.frontend.protos.BFEProtos.BFELoadLevelResponse, Builder>
        implements com.thilenius.blaze.frontend.protos.BFEProtos.BFELoadLevelResponseOrBuilder {
      // Construct using com.thilenius.blaze.frontend.protos.BFEProtos.BFELoadLevelResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        failureReason_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        sparkCount_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.thilenius.blaze.frontend.protos.BFEProtos.BFELoadLevelResponse getDefaultInstanceForType() {
        return com.thilenius.blaze.frontend.protos.BFEProtos.BFELoadLevelResponse.getDefaultInstance();
      }
      
      public com.thilenius.blaze.frontend.protos.BFEProtos.BFELoadLevelResponse build() {
        com.thilenius.blaze.frontend.protos.BFEProtos.BFELoadLevelResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.thilenius.blaze.frontend.protos.BFEProtos.BFELoadLevelResponse buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.thilenius.blaze.frontend.protos.BFEProtos.BFELoadLevelResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.thilenius.blaze.frontend.protos.BFEProtos.BFELoadLevelResponse buildPartial() {
        com.thilenius.blaze.frontend.protos.BFEProtos.BFELoadLevelResponse result = new com.thilenius.blaze.frontend.protos.BFEProtos.BFELoadLevelResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.failureReason_ = failureReason_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.sparkCount_ = sparkCount_;
        result.bitField0_ = to_bitField0_;
        return result;
      }
      
      public Builder mergeFrom(com.thilenius.blaze.frontend.protos.BFEProtos.BFELoadLevelResponse other) {
        if (other == com.thilenius.blaze.frontend.protos.BFEProtos.BFELoadLevelResponse.getDefaultInstance()) return this;
        if (other.hasFailureReason()) {
          setFailureReason(other.getFailureReason());
        }
        if (other.hasSparkCount()) {
          setSparkCount(other.getSparkCount());
        }
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              
              return this;
            default: {
              if (!parseUnknownField(input, extensionRegistry, tag)) {
                
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              failureReason_ = input.readBytes();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              sparkCount_ = input.readInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional string failure_reason = 1;
      private java.lang.Object failureReason_ = "";
      public boolean hasFailureReason() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getFailureReason() {
        java.lang.Object ref = failureReason_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          failureReason_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setFailureReason(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        failureReason_ = value;
        
        return this;
      }
      public Builder clearFailureReason() {
        bitField0_ = (bitField0_ & ~0x00000001);
        failureReason_ = getDefaultInstance().getFailureReason();
        
        return this;
      }
      void setFailureReason(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        failureReason_ = value;
        
      }
      
      // optional int32 spark_count = 2;
      private int sparkCount_ ;
      public boolean hasSparkCount() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public int getSparkCount() {
        return sparkCount_;
      }
      public Builder setSparkCount(int value) {
        bitField0_ |= 0x00000002;
        sparkCount_ = value;
        
        return this;
      }
      public Builder clearSparkCount() {
        bitField0_ = (bitField0_ & ~0x00000002);
        sparkCount_ = 0;
        
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:Thilenius.BFEProtos.BFELoadLevelResponse)
    }
    
    static {
      defaultInstance = new BFELoadLevelResponse(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:Thilenius.BFEProtos.BFELoadLevelResponse)
    public static final int BFELOADLEVELRESPONSE_EXT_FIELD_NUMBER = 101;
    public static final
      com.google.protobuf.GeneratedMessageLite.GeneratedExtension<
        com.thilenius.blaze.frontend.protos.BFEProtos.BFEMessage,
        com.thilenius.blaze.frontend.protos.BFEProtos.BFELoadLevelResponse> bFELoadLevelResponseExt = com.google.protobuf.GeneratedMessageLite
            .newSingularGeneratedExtension(
          com.thilenius.blaze.frontend.protos.BFEProtos.BFEMessage.getDefaultInstance(),
          com.thilenius.blaze.frontend.protos.BFEProtos.BFELoadLevelResponse.getDefaultInstance(),
          com.thilenius.blaze.frontend.protos.BFEProtos.BFELoadLevelResponse.getDefaultInstance(),
          null,
          101,
          com.google.protobuf.WireFormat.FieldType.MESSAGE);
  }
  
  public interface BFESparkCommandOrBuilder
      extends com.google.protobuf.MessageLiteOrBuilder {
    
    // required .Thilenius.BFEProtos.BFESparkCommand.CommandType command = 1;
    boolean hasCommand();
    com.thilenius.blaze.frontend.protos.BFEProtos.BFESparkCommand.CommandType getCommand();
    
    // required int32 spark_id = 2;
    boolean hasSparkId();
    int getSparkId();
    
    // required string auth_token = 3;
    boolean hasAuthToken();
    String getAuthToken();
    
    // optional string pipline_token = 4;
    boolean hasPiplineToken();
    String getPiplineToken();
  }
  public static final class BFESparkCommand extends
      com.google.protobuf.GeneratedMessageLite
      implements BFESparkCommandOrBuilder {
    // Use BFESparkCommand.newBuilder() to construct.
    private BFESparkCommand(Builder builder) {
      super(builder);
    }
    private BFESparkCommand(boolean noInit) {}
    
    private static final BFESparkCommand defaultInstance;
    public static BFESparkCommand getDefaultInstance() {
      return defaultInstance;
    }
    
    public BFESparkCommand getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public enum CommandType
        implements com.google.protobuf.Internal.EnumLite {
      MOVE_FORWARD(0, 0),
      MOVE_BACKWARD(1, 1),
      MOVE_UP(2, 2),
      MOVE_DOWN(3, 3),
      TURN_LEFT(4, 4),
      TURN_RIGHT(5, 5),
      ;
      
      public static final int MOVE_FORWARD_VALUE = 0;
      public static final int MOVE_BACKWARD_VALUE = 1;
      public static final int MOVE_UP_VALUE = 2;
      public static final int MOVE_DOWN_VALUE = 3;
      public static final int TURN_LEFT_VALUE = 4;
      public static final int TURN_RIGHT_VALUE = 5;
      
      
      public final int getNumber() { return value; }
      
      public static CommandType valueOf(int value) {
        switch (value) {
          case 0: return MOVE_FORWARD;
          case 1: return MOVE_BACKWARD;
          case 2: return MOVE_UP;
          case 3: return MOVE_DOWN;
          case 4: return TURN_LEFT;
          case 5: return TURN_RIGHT;
          default: return null;
        }
      }
      
      public static com.google.protobuf.Internal.EnumLiteMap<CommandType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<CommandType>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<CommandType>() {
              public CommandType findValueByNumber(int number) {
                return CommandType.valueOf(number);
              }
            };
      
      private final int value;
      
      private CommandType(int index, int value) {
        this.value = value;
      }
      
      // @@protoc_insertion_point(enum_scope:Thilenius.BFEProtos.BFESparkCommand.CommandType)
    }
    
    private int bitField0_;
    // required .Thilenius.BFEProtos.BFESparkCommand.CommandType command = 1;
    public static final int COMMAND_FIELD_NUMBER = 1;
    private com.thilenius.blaze.frontend.protos.BFEProtos.BFESparkCommand.CommandType command_;
    public boolean hasCommand() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public com.thilenius.blaze.frontend.protos.BFEProtos.BFESparkCommand.CommandType getCommand() {
      return command_;
    }
    
    // required int32 spark_id = 2;
    public static final int SPARK_ID_FIELD_NUMBER = 2;
    private int sparkId_;
    public boolean hasSparkId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public int getSparkId() {
      return sparkId_;
    }
    
    // required string auth_token = 3;
    public static final int AUTH_TOKEN_FIELD_NUMBER = 3;
    private java.lang.Object authToken_;
    public boolean hasAuthToken() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public String getAuthToken() {
      java.lang.Object ref = authToken_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          authToken_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getAuthTokenBytes() {
      java.lang.Object ref = authToken_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        authToken_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string pipline_token = 4;
    public static final int PIPLINE_TOKEN_FIELD_NUMBER = 4;
    private java.lang.Object piplineToken_;
    public boolean hasPiplineToken() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public String getPiplineToken() {
      java.lang.Object ref = piplineToken_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          piplineToken_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getPiplineTokenBytes() {
      java.lang.Object ref = piplineToken_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        piplineToken_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      command_ = com.thilenius.blaze.frontend.protos.BFEProtos.BFESparkCommand.CommandType.MOVE_FORWARD;
      sparkId_ = 0;
      authToken_ = "";
      piplineToken_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasCommand()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSparkId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasAuthToken()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, command_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, sparkId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getAuthTokenBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getPiplineTokenBytes());
      }
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, command_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, sparkId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getAuthTokenBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getPiplineTokenBytes());
      }
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.thilenius.blaze.frontend.protos.BFEProtos.BFESparkCommand parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.thilenius.blaze.frontend.protos.BFEProtos.BFESparkCommand parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.thilenius.blaze.frontend.protos.BFEProtos.BFESparkCommand parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.thilenius.blaze.frontend.protos.BFEProtos.BFESparkCommand parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.thilenius.blaze.frontend.protos.BFEProtos.BFESparkCommand parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.thilenius.blaze.frontend.protos.BFEProtos.BFESparkCommand parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.thilenius.blaze.frontend.protos.BFEProtos.BFESparkCommand parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.thilenius.blaze.frontend.protos.BFEProtos.BFESparkCommand parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.thilenius.blaze.frontend.protos.BFEProtos.BFESparkCommand parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.thilenius.blaze.frontend.protos.BFEProtos.BFESparkCommand parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.thilenius.blaze.frontend.protos.BFEProtos.BFESparkCommand prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.thilenius.blaze.frontend.protos.BFEProtos.BFESparkCommand, Builder>
        implements com.thilenius.blaze.frontend.protos.BFEProtos.BFESparkCommandOrBuilder {
      // Construct using com.thilenius.blaze.frontend.protos.BFEProtos.BFESparkCommand.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        command_ = com.thilenius.blaze.frontend.protos.BFEProtos.BFESparkCommand.CommandType.MOVE_FORWARD;
        bitField0_ = (bitField0_ & ~0x00000001);
        sparkId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        authToken_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        piplineToken_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.thilenius.blaze.frontend.protos.BFEProtos.BFESparkCommand getDefaultInstanceForType() {
        return com.thilenius.blaze.frontend.protos.BFEProtos.BFESparkCommand.getDefaultInstance();
      }
      
      public com.thilenius.blaze.frontend.protos.BFEProtos.BFESparkCommand build() {
        com.thilenius.blaze.frontend.protos.BFEProtos.BFESparkCommand result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.thilenius.blaze.frontend.protos.BFEProtos.BFESparkCommand buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.thilenius.blaze.frontend.protos.BFEProtos.BFESparkCommand result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.thilenius.blaze.frontend.protos.BFEProtos.BFESparkCommand buildPartial() {
        com.thilenius.blaze.frontend.protos.BFEProtos.BFESparkCommand result = new com.thilenius.blaze.frontend.protos.BFEProtos.BFESparkCommand(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.command_ = command_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.sparkId_ = sparkId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.authToken_ = authToken_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.piplineToken_ = piplineToken_;
        result.bitField0_ = to_bitField0_;
        return result;
      }
      
      public Builder mergeFrom(com.thilenius.blaze.frontend.protos.BFEProtos.BFESparkCommand other) {
        if (other == com.thilenius.blaze.frontend.protos.BFEProtos.BFESparkCommand.getDefaultInstance()) return this;
        if (other.hasCommand()) {
          setCommand(other.getCommand());
        }
        if (other.hasSparkId()) {
          setSparkId(other.getSparkId());
        }
        if (other.hasAuthToken()) {
          setAuthToken(other.getAuthToken());
        }
        if (other.hasPiplineToken()) {
          setPiplineToken(other.getPiplineToken());
        }
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasCommand()) {
          
          return false;
        }
        if (!hasSparkId()) {
          
          return false;
        }
        if (!hasAuthToken()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              
              return this;
            default: {
              if (!parseUnknownField(input, extensionRegistry, tag)) {
                
                return this;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              com.thilenius.blaze.frontend.protos.BFEProtos.BFESparkCommand.CommandType value = com.thilenius.blaze.frontend.protos.BFEProtos.BFESparkCommand.CommandType.valueOf(rawValue);
              if (value != null) {
                bitField0_ |= 0x00000001;
                command_ = value;
              }
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              sparkId_ = input.readInt32();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              authToken_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              piplineToken_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required .Thilenius.BFEProtos.BFESparkCommand.CommandType command = 1;
      private com.thilenius.blaze.frontend.protos.BFEProtos.BFESparkCommand.CommandType command_ = com.thilenius.blaze.frontend.protos.BFEProtos.BFESparkCommand.CommandType.MOVE_FORWARD;
      public boolean hasCommand() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public com.thilenius.blaze.frontend.protos.BFEProtos.BFESparkCommand.CommandType getCommand() {
        return command_;
      }
      public Builder setCommand(com.thilenius.blaze.frontend.protos.BFEProtos.BFESparkCommand.CommandType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        command_ = value;
        
        return this;
      }
      public Builder clearCommand() {
        bitField0_ = (bitField0_ & ~0x00000001);
        command_ = com.thilenius.blaze.frontend.protos.BFEProtos.BFESparkCommand.CommandType.MOVE_FORWARD;
        
        return this;
      }
      
      // required int32 spark_id = 2;
      private int sparkId_ ;
      public boolean hasSparkId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public int getSparkId() {
        return sparkId_;
      }
      public Builder setSparkId(int value) {
        bitField0_ |= 0x00000002;
        sparkId_ = value;
        
        return this;
      }
      public Builder clearSparkId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        sparkId_ = 0;
        
        return this;
      }
      
      // required string auth_token = 3;
      private java.lang.Object authToken_ = "";
      public boolean hasAuthToken() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public String getAuthToken() {
        java.lang.Object ref = authToken_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          authToken_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setAuthToken(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        authToken_ = value;
        
        return this;
      }
      public Builder clearAuthToken() {
        bitField0_ = (bitField0_ & ~0x00000004);
        authToken_ = getDefaultInstance().getAuthToken();
        
        return this;
      }
      void setAuthToken(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000004;
        authToken_ = value;
        
      }
      
      // optional string pipline_token = 4;
      private java.lang.Object piplineToken_ = "";
      public boolean hasPiplineToken() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public String getPiplineToken() {
        java.lang.Object ref = piplineToken_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          piplineToken_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setPiplineToken(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        piplineToken_ = value;
        
        return this;
      }
      public Builder clearPiplineToken() {
        bitField0_ = (bitField0_ & ~0x00000008);
        piplineToken_ = getDefaultInstance().getPiplineToken();
        
        return this;
      }
      void setPiplineToken(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000008;
        piplineToken_ = value;
        
      }
      
      // @@protoc_insertion_point(builder_scope:Thilenius.BFEProtos.BFESparkCommand)
    }
    
    static {
      defaultInstance = new BFESparkCommand(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:Thilenius.BFEProtos.BFESparkCommand)
    public static final int BFESPARKCOMMAND_EXT_FIELD_NUMBER = 102;
    public static final
      com.google.protobuf.GeneratedMessageLite.GeneratedExtension<
        com.thilenius.blaze.frontend.protos.BFEProtos.BFEMessage,
        com.thilenius.blaze.frontend.protos.BFEProtos.BFESparkCommand> bFESparkCommandExt = com.google.protobuf.GeneratedMessageLite
            .newSingularGeneratedExtension(
          com.thilenius.blaze.frontend.protos.BFEProtos.BFEMessage.getDefaultInstance(),
          com.thilenius.blaze.frontend.protos.BFEProtos.BFESparkCommand.getDefaultInstance(),
          com.thilenius.blaze.frontend.protos.BFEProtos.BFESparkCommand.getDefaultInstance(),
          null,
          102,
          com.google.protobuf.WireFormat.FieldType.MESSAGE);
  }
  
  public interface BFESparkResponseOrBuilder
      extends com.google.protobuf.MessageLiteOrBuilder {
    
    // optional string pipline_token = 1;
    boolean hasPiplineToken();
    String getPiplineToken();
    
    // optional string failure_reason = 2;
    boolean hasFailureReason();
    String getFailureReason();
    
    // optional bool response_bool = 3;
    boolean hasResponseBool();
    boolean getResponseBool();
    
    // optional int32 response_int = 4;
    boolean hasResponseInt();
    int getResponseInt();
    
    // optional float response_float = 5;
    boolean hasResponseFloat();
    float getResponseFloat();
    
    // optional bytes response_bytes = 6;
    boolean hasResponseBytes();
    com.google.protobuf.ByteString getResponseBytes();
  }
  public static final class BFESparkResponse extends
      com.google.protobuf.GeneratedMessageLite
      implements BFESparkResponseOrBuilder {
    // Use BFESparkResponse.newBuilder() to construct.
    private BFESparkResponse(Builder builder) {
      super(builder);
    }
    private BFESparkResponse(boolean noInit) {}
    
    private static final BFESparkResponse defaultInstance;
    public static BFESparkResponse getDefaultInstance() {
      return defaultInstance;
    }
    
    public BFESparkResponse getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    private int bitField0_;
    // optional string pipline_token = 1;
    public static final int PIPLINE_TOKEN_FIELD_NUMBER = 1;
    private java.lang.Object piplineToken_;
    public boolean hasPiplineToken() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getPiplineToken() {
      java.lang.Object ref = piplineToken_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          piplineToken_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getPiplineTokenBytes() {
      java.lang.Object ref = piplineToken_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        piplineToken_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string failure_reason = 2;
    public static final int FAILURE_REASON_FIELD_NUMBER = 2;
    private java.lang.Object failureReason_;
    public boolean hasFailureReason() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getFailureReason() {
      java.lang.Object ref = failureReason_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          failureReason_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getFailureReasonBytes() {
      java.lang.Object ref = failureReason_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        failureReason_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional bool response_bool = 3;
    public static final int RESPONSE_BOOL_FIELD_NUMBER = 3;
    private boolean responseBool_;
    public boolean hasResponseBool() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public boolean getResponseBool() {
      return responseBool_;
    }
    
    // optional int32 response_int = 4;
    public static final int RESPONSE_INT_FIELD_NUMBER = 4;
    private int responseInt_;
    public boolean hasResponseInt() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public int getResponseInt() {
      return responseInt_;
    }
    
    // optional float response_float = 5;
    public static final int RESPONSE_FLOAT_FIELD_NUMBER = 5;
    private float responseFloat_;
    public boolean hasResponseFloat() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public float getResponseFloat() {
      return responseFloat_;
    }
    
    // optional bytes response_bytes = 6;
    public static final int RESPONSE_BYTES_FIELD_NUMBER = 6;
    private com.google.protobuf.ByteString responseBytes_;
    public boolean hasResponseBytes() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    public com.google.protobuf.ByteString getResponseBytes() {
      return responseBytes_;
    }
    
    private void initFields() {
      piplineToken_ = "";
      failureReason_ = "";
      responseBool_ = false;
      responseInt_ = 0;
      responseFloat_ = 0F;
      responseBytes_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getPiplineTokenBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getFailureReasonBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBool(3, responseBool_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, responseInt_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeFloat(5, responseFloat_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, responseBytes_);
      }
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getPiplineTokenBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getFailureReasonBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, responseBool_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, responseInt_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(5, responseFloat_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, responseBytes_);
      }
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.thilenius.blaze.frontend.protos.BFEProtos.BFESparkResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.thilenius.blaze.frontend.protos.BFEProtos.BFESparkResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.thilenius.blaze.frontend.protos.BFEProtos.BFESparkResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.thilenius.blaze.frontend.protos.BFEProtos.BFESparkResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.thilenius.blaze.frontend.protos.BFEProtos.BFESparkResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.thilenius.blaze.frontend.protos.BFEProtos.BFESparkResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.thilenius.blaze.frontend.protos.BFEProtos.BFESparkResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.thilenius.blaze.frontend.protos.BFEProtos.BFESparkResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.thilenius.blaze.frontend.protos.BFEProtos.BFESparkResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.thilenius.blaze.frontend.protos.BFEProtos.BFESparkResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.thilenius.blaze.frontend.protos.BFEProtos.BFESparkResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.thilenius.blaze.frontend.protos.BFEProtos.BFESparkResponse, Builder>
        implements com.thilenius.blaze.frontend.protos.BFEProtos.BFESparkResponseOrBuilder {
      // Construct using com.thilenius.blaze.frontend.protos.BFEProtos.BFESparkResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        piplineToken_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        failureReason_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        responseBool_ = false;
        bitField0_ = (bitField0_ & ~0x00000004);
        responseInt_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        responseFloat_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000010);
        responseBytes_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.thilenius.blaze.frontend.protos.BFEProtos.BFESparkResponse getDefaultInstanceForType() {
        return com.thilenius.blaze.frontend.protos.BFEProtos.BFESparkResponse.getDefaultInstance();
      }
      
      public com.thilenius.blaze.frontend.protos.BFEProtos.BFESparkResponse build() {
        com.thilenius.blaze.frontend.protos.BFEProtos.BFESparkResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.thilenius.blaze.frontend.protos.BFEProtos.BFESparkResponse buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.thilenius.blaze.frontend.protos.BFEProtos.BFESparkResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.thilenius.blaze.frontend.protos.BFEProtos.BFESparkResponse buildPartial() {
        com.thilenius.blaze.frontend.protos.BFEProtos.BFESparkResponse result = new com.thilenius.blaze.frontend.protos.BFEProtos.BFESparkResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.piplineToken_ = piplineToken_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.failureReason_ = failureReason_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.responseBool_ = responseBool_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.responseInt_ = responseInt_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.responseFloat_ = responseFloat_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.responseBytes_ = responseBytes_;
        result.bitField0_ = to_bitField0_;
        return result;
      }
      
      public Builder mergeFrom(com.thilenius.blaze.frontend.protos.BFEProtos.BFESparkResponse other) {
        if (other == com.thilenius.blaze.frontend.protos.BFEProtos.BFESparkResponse.getDefaultInstance()) return this;
        if (other.hasPiplineToken()) {
          setPiplineToken(other.getPiplineToken());
        }
        if (other.hasFailureReason()) {
          setFailureReason(other.getFailureReason());
        }
        if (other.hasResponseBool()) {
          setResponseBool(other.getResponseBool());
        }
        if (other.hasResponseInt()) {
          setResponseInt(other.getResponseInt());
        }
        if (other.hasResponseFloat()) {
          setResponseFloat(other.getResponseFloat());
        }
        if (other.hasResponseBytes()) {
          setResponseBytes(other.getResponseBytes());
        }
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              
              return this;
            default: {
              if (!parseUnknownField(input, extensionRegistry, tag)) {
                
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              piplineToken_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              failureReason_ = input.readBytes();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              responseBool_ = input.readBool();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              responseInt_ = input.readInt32();
              break;
            }
            case 45: {
              bitField0_ |= 0x00000010;
              responseFloat_ = input.readFloat();
              break;
            }
            case 50: {
              bitField0_ |= 0x00000020;
              responseBytes_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional string pipline_token = 1;
      private java.lang.Object piplineToken_ = "";
      public boolean hasPiplineToken() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getPiplineToken() {
        java.lang.Object ref = piplineToken_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          piplineToken_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setPiplineToken(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        piplineToken_ = value;
        
        return this;
      }
      public Builder clearPiplineToken() {
        bitField0_ = (bitField0_ & ~0x00000001);
        piplineToken_ = getDefaultInstance().getPiplineToken();
        
        return this;
      }
      void setPiplineToken(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        piplineToken_ = value;
        
      }
      
      // optional string failure_reason = 2;
      private java.lang.Object failureReason_ = "";
      public boolean hasFailureReason() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getFailureReason() {
        java.lang.Object ref = failureReason_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          failureReason_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setFailureReason(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        failureReason_ = value;
        
        return this;
      }
      public Builder clearFailureReason() {
        bitField0_ = (bitField0_ & ~0x00000002);
        failureReason_ = getDefaultInstance().getFailureReason();
        
        return this;
      }
      void setFailureReason(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        failureReason_ = value;
        
      }
      
      // optional bool response_bool = 3;
      private boolean responseBool_ ;
      public boolean hasResponseBool() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public boolean getResponseBool() {
        return responseBool_;
      }
      public Builder setResponseBool(boolean value) {
        bitField0_ |= 0x00000004;
        responseBool_ = value;
        
        return this;
      }
      public Builder clearResponseBool() {
        bitField0_ = (bitField0_ & ~0x00000004);
        responseBool_ = false;
        
        return this;
      }
      
      // optional int32 response_int = 4;
      private int responseInt_ ;
      public boolean hasResponseInt() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public int getResponseInt() {
        return responseInt_;
      }
      public Builder setResponseInt(int value) {
        bitField0_ |= 0x00000008;
        responseInt_ = value;
        
        return this;
      }
      public Builder clearResponseInt() {
        bitField0_ = (bitField0_ & ~0x00000008);
        responseInt_ = 0;
        
        return this;
      }
      
      // optional float response_float = 5;
      private float responseFloat_ ;
      public boolean hasResponseFloat() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public float getResponseFloat() {
        return responseFloat_;
      }
      public Builder setResponseFloat(float value) {
        bitField0_ |= 0x00000010;
        responseFloat_ = value;
        
        return this;
      }
      public Builder clearResponseFloat() {
        bitField0_ = (bitField0_ & ~0x00000010);
        responseFloat_ = 0F;
        
        return this;
      }
      
      // optional bytes response_bytes = 6;
      private com.google.protobuf.ByteString responseBytes_ = com.google.protobuf.ByteString.EMPTY;
      public boolean hasResponseBytes() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      public com.google.protobuf.ByteString getResponseBytes() {
        return responseBytes_;
      }
      public Builder setResponseBytes(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        responseBytes_ = value;
        
        return this;
      }
      public Builder clearResponseBytes() {
        bitField0_ = (bitField0_ & ~0x00000020);
        responseBytes_ = getDefaultInstance().getResponseBytes();
        
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:Thilenius.BFEProtos.BFESparkResponse)
    }
    
    static {
      defaultInstance = new BFESparkResponse(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:Thilenius.BFEProtos.BFESparkResponse)
    public static final int BFESPARKRESPONSE_EXT_FIELD_NUMBER = 103;
    public static final
      com.google.protobuf.GeneratedMessageLite.GeneratedExtension<
        com.thilenius.blaze.frontend.protos.BFEProtos.BFEMessage,
        com.thilenius.blaze.frontend.protos.BFEProtos.BFESparkResponse> bFESparkResponseExt = com.google.protobuf.GeneratedMessageLite
            .newSingularGeneratedExtension(
          com.thilenius.blaze.frontend.protos.BFEProtos.BFEMessage.getDefaultInstance(),
          com.thilenius.blaze.frontend.protos.BFEProtos.BFESparkResponse.getDefaultInstance(),
          com.thilenius.blaze.frontend.protos.BFEProtos.BFESparkResponse.getDefaultInstance(),
          null,
          103,
          com.google.protobuf.WireFormat.FieldType.MESSAGE);
  }
  
  
  static {
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
