/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef Flame_H
#define Flame_H

#include <thrift/TDispatchProcessor.h>
#include "Flame_types.h"

namespace Flame {

class FlameIf {
 public:
  virtual ~FlameIf() {}
  virtual void CreateSpark(Spark& _return, const Location& worldLocation) = 0;
  virtual void GetAllSparks(std::vector<Spark> & _return) = 0;
  virtual void RemoveSpark(const Spark& sparkToRemove) = 0;
  virtual void RemoveAllSparks() = 0;
  virtual bool DispatchMovementCommand(const Spark& spark, const MovementTypes::type movementCommand) = 0;
};

class FlameIfFactory {
 public:
  typedef FlameIf Handler;

  virtual ~FlameIfFactory() {}

  virtual FlameIf* getHandler(const ::apache::thrift::TConnectionInfo& connInfo) = 0;
  virtual void releaseHandler(FlameIf* /* handler */) = 0;
};

class FlameIfSingletonFactory : virtual public FlameIfFactory {
 public:
  FlameIfSingletonFactory(const boost::shared_ptr<FlameIf>& iface) : iface_(iface) {}
  virtual ~FlameIfSingletonFactory() {}

  virtual FlameIf* getHandler(const ::apache::thrift::TConnectionInfo&) {
    return iface_.get();
  }
  virtual void releaseHandler(FlameIf* /* handler */) {}

 protected:
  boost::shared_ptr<FlameIf> iface_;
};

class FlameNull : virtual public FlameIf {
 public:
  virtual ~FlameNull() {}
  void CreateSpark(Spark& /* _return */, const Location& /* worldLocation */) {
    return;
  }
  void GetAllSparks(std::vector<Spark> & /* _return */) {
    return;
  }
  void RemoveSpark(const Spark& /* sparkToRemove */) {
    return;
  }
  void RemoveAllSparks() {
    return;
  }
  bool DispatchMovementCommand(const Spark& /* spark */, const MovementTypes::type /* movementCommand */) {
    bool _return = false;
    return _return;
  }
};

typedef struct _Flame_CreateSpark_args__isset {
  _Flame_CreateSpark_args__isset() : worldLocation(false) {}
  bool worldLocation;
} _Flame_CreateSpark_args__isset;

class Flame_CreateSpark_args {
 public:

  Flame_CreateSpark_args() {
  }

  virtual ~Flame_CreateSpark_args() throw() {}

  Location worldLocation;

  _Flame_CreateSpark_args__isset __isset;

  void __set_worldLocation(const Location& val) {
    worldLocation = val;
  }

  bool operator == (const Flame_CreateSpark_args & rhs) const
  {
    if (!(worldLocation == rhs.worldLocation))
      return false;
    return true;
  }
  bool operator != (const Flame_CreateSpark_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Flame_CreateSpark_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class Flame_CreateSpark_pargs {
 public:


  virtual ~Flame_CreateSpark_pargs() throw() {}

  const Location* worldLocation;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Flame_CreateSpark_result__isset {
  _Flame_CreateSpark_result__isset() : success(false) {}
  bool success;
} _Flame_CreateSpark_result__isset;

class Flame_CreateSpark_result {
 public:

  Flame_CreateSpark_result() {
  }

  virtual ~Flame_CreateSpark_result() throw() {}

  Spark success;

  _Flame_CreateSpark_result__isset __isset;

  void __set_success(const Spark& val) {
    success = val;
  }

  bool operator == (const Flame_CreateSpark_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const Flame_CreateSpark_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Flame_CreateSpark_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Flame_CreateSpark_presult__isset {
  _Flame_CreateSpark_presult__isset() : success(false) {}
  bool success;
} _Flame_CreateSpark_presult__isset;

class Flame_CreateSpark_presult {
 public:


  virtual ~Flame_CreateSpark_presult() throw() {}

  Spark* success;

  _Flame_CreateSpark_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};


class Flame_GetAllSparks_args {
 public:

  Flame_GetAllSparks_args() {
  }

  virtual ~Flame_GetAllSparks_args() throw() {}


  bool operator == (const Flame_GetAllSparks_args & /* rhs */) const
  {
    return true;
  }
  bool operator != (const Flame_GetAllSparks_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Flame_GetAllSparks_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class Flame_GetAllSparks_pargs {
 public:


  virtual ~Flame_GetAllSparks_pargs() throw() {}


  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Flame_GetAllSparks_result__isset {
  _Flame_GetAllSparks_result__isset() : success(false) {}
  bool success;
} _Flame_GetAllSparks_result__isset;

class Flame_GetAllSparks_result {
 public:

  Flame_GetAllSparks_result() {
  }

  virtual ~Flame_GetAllSparks_result() throw() {}

  std::vector<Spark>  success;

  _Flame_GetAllSparks_result__isset __isset;

  void __set_success(const std::vector<Spark> & val) {
    success = val;
  }

  bool operator == (const Flame_GetAllSparks_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const Flame_GetAllSparks_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Flame_GetAllSparks_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Flame_GetAllSparks_presult__isset {
  _Flame_GetAllSparks_presult__isset() : success(false) {}
  bool success;
} _Flame_GetAllSparks_presult__isset;

class Flame_GetAllSparks_presult {
 public:


  virtual ~Flame_GetAllSparks_presult() throw() {}

  std::vector<Spark> * success;

  _Flame_GetAllSparks_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _Flame_RemoveSpark_args__isset {
  _Flame_RemoveSpark_args__isset() : sparkToRemove(false) {}
  bool sparkToRemove;
} _Flame_RemoveSpark_args__isset;

class Flame_RemoveSpark_args {
 public:

  Flame_RemoveSpark_args() {
  }

  virtual ~Flame_RemoveSpark_args() throw() {}

  Spark sparkToRemove;

  _Flame_RemoveSpark_args__isset __isset;

  void __set_sparkToRemove(const Spark& val) {
    sparkToRemove = val;
  }

  bool operator == (const Flame_RemoveSpark_args & rhs) const
  {
    if (!(sparkToRemove == rhs.sparkToRemove))
      return false;
    return true;
  }
  bool operator != (const Flame_RemoveSpark_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Flame_RemoveSpark_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class Flame_RemoveSpark_pargs {
 public:


  virtual ~Flame_RemoveSpark_pargs() throw() {}

  const Spark* sparkToRemove;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class Flame_RemoveSpark_result {
 public:

  Flame_RemoveSpark_result() {
  }

  virtual ~Flame_RemoveSpark_result() throw() {}


  bool operator == (const Flame_RemoveSpark_result & /* rhs */) const
  {
    return true;
  }
  bool operator != (const Flame_RemoveSpark_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Flame_RemoveSpark_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class Flame_RemoveSpark_presult {
 public:


  virtual ~Flame_RemoveSpark_presult() throw() {}


  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};


class Flame_RemoveAllSparks_args {
 public:

  Flame_RemoveAllSparks_args() {
  }

  virtual ~Flame_RemoveAllSparks_args() throw() {}


  bool operator == (const Flame_RemoveAllSparks_args & /* rhs */) const
  {
    return true;
  }
  bool operator != (const Flame_RemoveAllSparks_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Flame_RemoveAllSparks_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class Flame_RemoveAllSparks_pargs {
 public:


  virtual ~Flame_RemoveAllSparks_pargs() throw() {}


  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class Flame_RemoveAllSparks_result {
 public:

  Flame_RemoveAllSparks_result() {
  }

  virtual ~Flame_RemoveAllSparks_result() throw() {}


  bool operator == (const Flame_RemoveAllSparks_result & /* rhs */) const
  {
    return true;
  }
  bool operator != (const Flame_RemoveAllSparks_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Flame_RemoveAllSparks_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class Flame_RemoveAllSparks_presult {
 public:


  virtual ~Flame_RemoveAllSparks_presult() throw() {}


  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _Flame_DispatchMovementCommand_args__isset {
  _Flame_DispatchMovementCommand_args__isset() : spark(false), movementCommand(false) {}
  bool spark;
  bool movementCommand;
} _Flame_DispatchMovementCommand_args__isset;

class Flame_DispatchMovementCommand_args {
 public:

  Flame_DispatchMovementCommand_args() : movementCommand((MovementTypes::type)0) {
  }

  virtual ~Flame_DispatchMovementCommand_args() throw() {}

  Spark spark;
  MovementTypes::type movementCommand;

  _Flame_DispatchMovementCommand_args__isset __isset;

  void __set_spark(const Spark& val) {
    spark = val;
  }

  void __set_movementCommand(const MovementTypes::type val) {
    movementCommand = val;
  }

  bool operator == (const Flame_DispatchMovementCommand_args & rhs) const
  {
    if (!(spark == rhs.spark))
      return false;
    if (!(movementCommand == rhs.movementCommand))
      return false;
    return true;
  }
  bool operator != (const Flame_DispatchMovementCommand_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Flame_DispatchMovementCommand_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class Flame_DispatchMovementCommand_pargs {
 public:


  virtual ~Flame_DispatchMovementCommand_pargs() throw() {}

  const Spark* spark;
  const MovementTypes::type* movementCommand;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Flame_DispatchMovementCommand_result__isset {
  _Flame_DispatchMovementCommand_result__isset() : success(false) {}
  bool success;
} _Flame_DispatchMovementCommand_result__isset;

class Flame_DispatchMovementCommand_result {
 public:

  Flame_DispatchMovementCommand_result() : success(0) {
  }

  virtual ~Flame_DispatchMovementCommand_result() throw() {}

  bool success;

  _Flame_DispatchMovementCommand_result__isset __isset;

  void __set_success(const bool val) {
    success = val;
  }

  bool operator == (const Flame_DispatchMovementCommand_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const Flame_DispatchMovementCommand_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Flame_DispatchMovementCommand_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Flame_DispatchMovementCommand_presult__isset {
  _Flame_DispatchMovementCommand_presult__isset() : success(false) {}
  bool success;
} _Flame_DispatchMovementCommand_presult__isset;

class Flame_DispatchMovementCommand_presult {
 public:


  virtual ~Flame_DispatchMovementCommand_presult() throw() {}

  bool* success;

  _Flame_DispatchMovementCommand_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

class FlameClient : virtual public FlameIf {
 public:
  FlameClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) :
    piprot_(prot),
    poprot_(prot) {
    iprot_ = prot.get();
    oprot_ = prot.get();
  }
  FlameClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) :
    piprot_(iprot),
    poprot_(oprot) {
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void CreateSpark(Spark& _return, const Location& worldLocation);
  void send_CreateSpark(const Location& worldLocation);
  void recv_CreateSpark(Spark& _return);
  void GetAllSparks(std::vector<Spark> & _return);
  void send_GetAllSparks();
  void recv_GetAllSparks(std::vector<Spark> & _return);
  void RemoveSpark(const Spark& sparkToRemove);
  void send_RemoveSpark(const Spark& sparkToRemove);
  void recv_RemoveSpark();
  void RemoveAllSparks();
  void send_RemoveAllSparks();
  void recv_RemoveAllSparks();
  bool DispatchMovementCommand(const Spark& spark, const MovementTypes::type movementCommand);
  void send_DispatchMovementCommand(const Spark& spark, const MovementTypes::type movementCommand);
  bool recv_DispatchMovementCommand();
 protected:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
};

class FlameProcessor : public ::apache::thrift::TDispatchProcessor {
 protected:
  boost::shared_ptr<FlameIf> iface_;
  virtual bool dispatchCall(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, const std::string& fname, int32_t seqid, void* callContext);
 private:
  typedef  void (FlameProcessor::*ProcessFunction)(int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*, void*);
  typedef std::map<std::string, ProcessFunction> ProcessMap;
  ProcessMap processMap_;
  void process_CreateSpark(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_GetAllSparks(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_RemoveSpark(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_RemoveAllSparks(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_DispatchMovementCommand(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
 public:
  FlameProcessor(boost::shared_ptr<FlameIf> iface) :
    iface_(iface) {
    processMap_["CreateSpark"] = &FlameProcessor::process_CreateSpark;
    processMap_["GetAllSparks"] = &FlameProcessor::process_GetAllSparks;
    processMap_["RemoveSpark"] = &FlameProcessor::process_RemoveSpark;
    processMap_["RemoveAllSparks"] = &FlameProcessor::process_RemoveAllSparks;
    processMap_["DispatchMovementCommand"] = &FlameProcessor::process_DispatchMovementCommand;
  }

  virtual ~FlameProcessor() {}
};

class FlameProcessorFactory : public ::apache::thrift::TProcessorFactory {
 public:
  FlameProcessorFactory(const ::boost::shared_ptr< FlameIfFactory >& handlerFactory) :
      handlerFactory_(handlerFactory) {}

  ::boost::shared_ptr< ::apache::thrift::TProcessor > getProcessor(const ::apache::thrift::TConnectionInfo& connInfo);

 protected:
  ::boost::shared_ptr< FlameIfFactory > handlerFactory_;
};

class FlameMultiface : virtual public FlameIf {
 public:
  FlameMultiface(std::vector<boost::shared_ptr<FlameIf> >& ifaces) : ifaces_(ifaces) {
  }
  virtual ~FlameMultiface() {}
 protected:
  std::vector<boost::shared_ptr<FlameIf> > ifaces_;
  FlameMultiface() {}
  void add(boost::shared_ptr<FlameIf> iface) {
    ifaces_.push_back(iface);
  }
 public:
  void CreateSpark(Spark& _return, const Location& worldLocation) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->CreateSpark(_return, worldLocation);
    }
    ifaces_[i]->CreateSpark(_return, worldLocation);
    return;
  }

  void GetAllSparks(std::vector<Spark> & _return) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->GetAllSparks(_return);
    }
    ifaces_[i]->GetAllSparks(_return);
    return;
  }

  void RemoveSpark(const Spark& sparkToRemove) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->RemoveSpark(sparkToRemove);
    }
    ifaces_[i]->RemoveSpark(sparkToRemove);
  }

  void RemoveAllSparks() {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->RemoveAllSparks();
    }
    ifaces_[i]->RemoveAllSparks();
  }

  bool DispatchMovementCommand(const Spark& spark, const MovementTypes::type movementCommand) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->DispatchMovementCommand(spark, movementCommand);
    }
    return ifaces_[i]->DispatchMovementCommand(spark, movementCommand);
  }

};

} // namespace

#endif
